@host = http://localhost:3000

GET {{host}}/api/autores?page=1&limit=5

###
GET {{host}}/api/posts?page=1&limit=5

### 
GET {{host}}/api/autores/39

###
GET {{host}}/api/posts/6

###
GET {{host}}/api/posts/author/5

### 
POST {{host}}/api/autores
Content-Type: application/json

{
    "nombre": "Gael Mascaro",
    "email": "gael@example14.com",
    "imagen": "https://e00-expansion.uecdn.es/assets/multimedia/imagenes/2023/05/18/16844078837232.jpg"
}

###
POST {{host}}/api/posts
Content-Type: application/json

{
    "titulo": "La casa roja",
    "descripcion":"Narra la historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo",
    "fecha_creacion": "1990-03-25",
    "categoria": "Novela Magico",
    "autores_id": 5

}

